steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/pendo-io/stage-regression-alerter.git', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - '$_IMAGE'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE']

images:
  - '$_IMAGE'
